apiVersion: apps/v1
kind: Deployment
metadata:
  name: wcfclient-deployment-2022
  labels:
    name: wcfclient-deployment-2022
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wcfclient
  template:
    metadata:
      labels:
        app: wcfclient
    spec:
      containers:
      - name: wcfclient
        image: rbcwcfclienttestacr.azurecr.io/rbc/wcftestclient:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "500Mi"
            cpu: 1
          limits:
            memory: "1024Mi"
            cpu: 1
---
apiVersion: v1
kind: Service
metadata:
  name: wcfclient-service
spec:
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 80
  selector:
    app: wcfclient